volumes:
  postgres-data:
    external: true
  pg-admin:
    external: true
  jwtdown-db-data:
    external: true
services:
  postgres:
    image: postgres:14.2-bullseye
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=facebark
      - POSTGRES_USER=facebark
      - POSTGRES_PASSWORD=password
    ports:
      - 15432:5432
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: facebark@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: 1
  facebark:
    build:
        context: ./facebark
        dockerfile: ./Dockerfile.dev
    ports:
        - "8000:8000"
    volumes:
        - ./facebark:/app
    environment:
      SIGNING_KEY: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY3NjkzMDc5MSwiaWF0IjoxNjc2OTMwNzkxfQ.IS0uv-T4hBkH_Jn2JtVe7zKu0FiiOYYSotKxLTfWKmE
      DATABASE_URL: postgresql://facebark:password@postgres/facebark
      WAIT_HOSTS: postgres:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_FACEBARK_API_HOST: http://localhost:8000
